### ISSUE TITLE
Lijst van teleurstellingen

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bevragen#1598]
De volgende scenarios falen nu wegens verkeerde verwachtingen of door fouten in de scenario zelf:

- [x] features\gba-dev\waardetabel-gba.feature:88 
    - Een verkorte field wordt gebruikt. Melvin zegt deze al te hebben aangepast.
- [X] features\bevragen\autorisatie-gba.feature:398 (Scenario: Gemeente is niet geautoriseerd voor de zoekparameters maar zoekt alleen eigen inwoners
    - Achtergrond ontbreekt --> toegevoegd met #1594
- [x] features\bevragen\persoon\adressering\adres-regels\dev\autorisatie-gba.feature:171 (Scenario: Afnemer vraagt om adressering.adresregel3 en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen)
    - Dankzij de autorisaties zal de API ook geen data hebben om een verblijfplaats te mappen dus een lege verblijfplaats object is incorrect. --> opgelost met #1595
- [x] features\bevragen\persoon\adressering\adres-regels\dev\autorisatie-gba.feature:213 (Scenario: Afnemer vraagt om adressering.land en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen)
    - Dankzij de autorisaties zal de API ook geen data hebben om een verblijfplaats te mappen dus een lege verblijfplaats object is incorrect. --> opgelost met #1595
- [X] features\bevragen\persoon-beperkt\adressering\adres-regels\dev\autorisatie-gba.feature:181 (Scenario: Afnemer vraagt om adressering.adresregel3 en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen)
    - Dankzij de autorisaties zal de API ook geen data hebben om een verblijfplaats te mappen dus een lege verblijfplaats object is incorrect. --> opgelost met #1595
- [X] features\bevragen\persoon-beperkt\adressering\adres-regels\dev\autorisatie-gba.feature:225 (Scenario: Afnemer vraagt om adressering.land en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen)
    - Dankzij de autorisaties zal de API ook geen data hebben om een verblijfplaats te mappen dus een lege verblijfplaats object is incorrect. --> opgelost met #1595 
- [X] features\bevragen\autorisatie-gba.feature:249 (Scenario: Afnemer zonder autorisatie voor historische aangaanHuwelijkPartnerschap (550610) vraagt om partner aangaanHuwelijkPartnerschap van persoon met actuele partner)
        - Deze zou worden verwijderd? --> wordt verwijderd met #1563

- [x] De volgende drie hebben verschillende titels voor dezelfde foutcode --> opgelost met #1594
  - features\bevragen\autorisatie-gba.feature:516 (Scenario: Autorisatie voor ad hoc gegevensverstrekking is ingetrokken)      
  - features\bevragen\autorisatie-gba.feature:661 (Scenario: Autorisatie voor ad hoc gegevensverstrekking gaat morgen in)
  - features\bevragen\autorisatie-gba.feature:44 (Scenario: Afnemer is niet geautoriseerd voor ad hoc gegevensverstrekking)

- [X] RNI geen gegevens: --> wordt opgelost met #1596
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:261
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:262
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:284
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:285
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:286
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:306
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:307
  - features\bevragen\persoon\rni\dev\overzicht-gba.feature:308

- [x] De volgende feature/scenarios kunnen niet worden getest:
  - features\bevragen\persoon\adressering\aanhef\dev\gba.feature --> wordt opgelost met #1610
  - features\bevragen\zoek-met-geslachtsnaam-en-geboortedatum\dev\gba.feature:29

### Toegevoegd 08-02-2023
- [X] Volgorde parameters moeten alfabetisch --> wordt opgelost met #1600
   - features\bevragen\zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving\dev\parameter-autorisatie-gba.feature:64
   - features\bevragen\zoek-met-geslachtsnaam-en-geboortedatum\dev\parameter-autorisatie-gba.feature:68

- [x] Niet voldoende rechten --> wordt opgelost met #1603 en #1606
    - features\bevragen\zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving\dev\parameter-autorisatie-gba.feature:128
    - features\bevragen\zoek-met-geslachtsnaam-voornamen-en-gemeente-van-inschrijving\dev\parameter-autorisatie-gba.feature:129	
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:32
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:33
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:34
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:35
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:36
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:37
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:38
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:39
    - features\bevragen\persoon-beperkt\verificatie\dev\autorisatie-gba.feature:40

- [X] Scenario notatie fouten --> wordt opgelost met #1607
    - features\bevragen\persoon\europees-kiesrecht\dev\fields-gba.feature:6 (Als gba personen)
    - features\bevragen\zoek-met-geslachtsnaam-en-geboortedatum\dev\gba.feature:29 (Als gba personen + geslachtsaanduiding dat niet geslacht mag zijn.)

### Toegevoegd 14-02-2023
- [x] BSN scenario komt niet overeen met achtergrond waardoor niks kan worden gevonden --> wordt opgelost met #1619
    - features\bevragen\persoon\adressering\aanschrijfwijze\dev\fields-gba.feature
    - features\bevragen\persoon\adressering\gebruikinlopendetekst\dev\fields-gba.feature
- [x] Adressering/aanhef, aanschrijfwijze, gebruikInLopendeTekst horen aangaanHuwelijkPartnerschap/ontbindingHuwelijkPartnerschap aan te leveren volgens fields-gba van deze onderwerpen. Echter bij de volgende feature kan geen inOnderzoek worden getoond van bijv. aangaanHuwelijkPartnerschap
    - features\bevragen\persoon\adressering\dev\fields-gba.feature
        - Dit is toch niet logisch? We hebben afspraken dat als je een bevraging doet van een object dat in onderzoek is, dat je automatisch het in onderzoek stuk terug krijgt? Door bijv. adressering.aanschrijfwijze te vragen in de fields, krijg je gegevens van aangaanHuwelijkPartnerschap terug en dus ook inOnderzoek.
- [x] Immigratie.inOnderzoek is een proxy field en wordt vertaald bij de GBA naar verblijfplaats.inOnderzoek.
    - features\bevragen\persoon\rni\dev\overzicht-gba.feature:191
        - Hier dient er geen lege verblijfplaats object te worden getoond, echter aangezien de field verblijfplaats.inOnderzoek wordt gebruikt en er geen inOnderzoek waarde is, zal dit een leeg object leveren. inOnderzoek moet daarentegen worden genegeerd. Wat te doen in deze casus? Moet heel immigratie.inOnderzoek worden genegeerd?
- [x] Moet deze field worden genegeerd? --> wordt opgelost met #1617
     - features\bevragen\persoon\rni\dev\overzicht-gba.feature:192
- [x] Gebruikte fields bestaan niet in de beperkt persoon vorm --> wordt opgelost met  #1617
    - features\bevragen\persoon-beperkt\rni\dev\overzicht-gba.feature:167
    - features\bevragen\persoon-beperkt\rni\dev\overzicht-gba.feature:168
- [x] Volgorde fout params niet volgens afspraak (alfabetisch hoort dit te zijn.) --> wordt opgelost met #1620
    - features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:9
    - features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:66
- [x] Foutmelding binnen scenario klopt niet. 0 en 100000 zijn getallen dus waarom is deze niet geldig?
    - features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:136
    - features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:137
    - features\bevragen\zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving\dev\fout-cases-gba.feature:144
    - features\bevragen\zoek-met-straatnaam-huisnummer-en-gemeente-van-inschrijving\dev\fout-cases-gba.feature:145

#### GBA API versie: 2.0.26
- [x] Typefouten protocollering scenarios --> wordt opgelost met #1622
    - features\bevragen\protocollering-gba.feature:100 (Scenario: Gevraagde veld <fields veld> wordt vastgelegd in 'request_gevraagde_rubrieken' als <rubrieknummer>)
        - partners.naam.geslachtsnaam is niet 050140 maar 050240.
    - features\bevragen\protocollering-gba.feature:181 (Scenario: vragen om <fields>)
        - Field 'ouders.datumIngangFamilierechtelijkeBetrekking' heeft een incorrecte rubriek staan. Moet 026210 zijn ipv 0206210.
    - features\bevragen\protocollering-gba.feature:141 (Scenario: vragen om hele relatie <relatie>)
        - partners en kinderen missen een komma na de eerste rubriek.
    - features\bevragen\protocollering-gba.feature:234 (Scenario: Persoon heeft geheimhouding, opschorting, in onderzoek, RNI en verificatie)
        - De inserts voor datum en omschrijving verificatie zijn onjuist. 'Datum verificatie (71.10)' moet worden 'datum verificatie (71.10)' en 'Omschrijving verificatie (71.20)' moet worden 'omschrijving verificatie (71.20)'.

- [x] Run fouten protocollering scenarios --> wordt opgelost met #1622
    - features\bevragen\protocollering-gba.feature:328 (Scenario: Zoek persoon met alle mogelijke parameters)
        - Geslacht wordt gevraagd. Niet gezocht. Waarom zou 010410 in de request_zoek_rubrieken staan?
    - features\bevragen\zoek-met-geslachtsnaam-en-geboortedatum\dev\protocollering-zoek-rubrieken-gba.feature(Abstract Scenario: zoek persoon met postcode, huisnummer en <zoekparameter>)
        - Scenario bevat geen fields dus zal er constant een 400 foutmelding ontstaan.

- [x] Verkeerde conclusies rondom rubrieken
    - features\bevragen\protocollering-gba.feature:137 (Scenario: vragen om hele groep <groep>)
        - Fields bevat de gehele groep. inOnderzoek maakt daar onderdeel van uit dus xx8310 en xx8320 horen bij de request_gevraagde_rubrieken.
    - features\bevragen\protocollering-gba.feature:156 (Scenario: vragen om hele relatie partners)
        - Soort verbintenis maakt onderdeel uit van partners en ook hier inOnderzoek idem.
    - features\bevragen\protocollering-gba.feature:157 (Scenario: vragen om hele relatie kinderen)
        - Geboorteland kind maakt onderdeel uit van kinderen en ook hier inOnderzoek idem.
    - features\bevragen\protocollering-gba.feature:224 (Scenario: Vragen om naam en persoon heeft geen adellijkeTitelPredicaat)
        - Fields naam omvat ook geslachtsnaam en aanduiding naamgebruik.
    - features\bevragen\protocollering-gba.feature:278 (Abstract Scenario: Vragen om <fields>)
        - verblijfplaats.datumVan is niet alleen datumAanvangAdreshouding en datumAanvangAdresBuitenland volgens fields-gba, maar ook straat, locatiebeschrijving en land
    - features\bevragen\protocollering-gba.feature:279 (Abstract Scenario: Vragen om <fields>)
        - adressering.aanschrijfwijze vertaalt naar 'naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap&partners.ontbindingHuwelijkPartnerschap'
    - features\bevragen\protocollering-gba.feature:282 (Abstract Scenario: Vragen om <fields>)
        - partners.aangaanHuwelijkPartnerschap heeft meer dan alleen 050610 (050620, 050630)
        - Moet 550510 hier ook geleverd worden omdat we soms deze gegeven uit de historie moeten halen?
    - features\bevragen\protocollering-gba.feature:322 (Abstract Scenario: Vragen om <fields> protocolleert ook benodigde velden voor het type)
        - Veel rubrieken ontbreken in de scenario aangezien deze volgens fields-gba wel moeten worden geleverd bij deze field bevraging.
    - features\bevragen\persoon\verblijfplaats\dev\protocollering-gevraagde-rubrieken-gba.feature:56 (Scenario: Met fields vragen om verblijfplaatsBinnenland.verblijfadres wordt vastgelegd als gevraagde rubrieken 081110, 081115, 081120, 081130, 081140, 081150, 081160, 081170, 081210)
        - fields-gba features geven nergens aan dat 'verblijfplaatsBinnenland.verblijfadres' naamOpenbareRuimte en aanduiding bij huisnummer moet omvatten.

##### Fields die de GBA API nooit zou ontvangen --> opgelost in #1640 en #1654
- [x] features\bevragen\fields-fout-cases-gba.feature (Scenario: Automatisch geleverd veld <fields> mag niet worden gevraagd bij zoeken) 
- [x] Scenario: naam veld(en) van partner is/zijn in onderzoek # features\bevragen\persoon\partner\dev\fields-gba.feature:36
- [x] Scenario: burgerservicenummer is in onderzoek # features\bevragen\persoon\partner\dev\fields-gba.feature:58
- [x] Scenario: 'gezagsverhouding' veld(en) van persoon is/zijn in onderzoek # features\bevragen\persoon\gezagsverhouding\dev\gezagsverhouding-gba.feature
- [x] Scenario: geboorte veld(en) van persoon is/zijn in onderzoek # features\bevragen\persoon\geboorte\dev\in-onderzoek-gba.feature:24
- [x] Scenario: Automatisch geleverd veld partners.aangaanHuwelijkPartnerschap.inOnderzoek.datum mag niet worden gevraagd bij raadplegen # features\bevragen\fields-fout-cases-gba.feature
- [x] Scenario: Automatisch geleverd veld naam.inOnderzoek.voornamen mag niet worden gevraagd bij zoeken # features\bevragen\fields-fout-cases-gba.feature

##### Lege partners array wordt niet verwacht, echter de genoemde fields vertaalt naar o.a. een partner gegeven. --> opgelost in #1650
- [x] features\bevragen\persoon\adressering\dev\fields-gba.feature
    - Het is dus vrij logisch dat een lege partners array wordt getoond als er geen gegeven is voor partner maar wel iets wordt gevraagd.

##### Een genoemde rule is misleidend --> opgelost in #1651
- [x] features\bevragen\persoon\ouders\dev\autorisatie-gba
    - De volgende rule (Rule: Vragen met fields gevraagd wordt om ouders.ouderAanduiding, wanneer de afnemer niet geautoriseerd is voor ten minste één gegeven van ouder 1 én ten minste één gegeven van ouder 2, geeft een foutmelding) moet worden gewijzigd. Iedereen heeft immers rechten op inOnderzoek van ouders dus volgens deze rule zal de scenario 'Abstract Scenario: Afnemer is <missende autorisatie>' altijd falen want er zijn by default inOnderzoek impliciete kenmerken.

##### Fout in de scenario rondom rubrieknummer --> opgelost in #1652
- [x] Scenario: kindgegevens zijn gecorrigeerd (zijn onjuist) en afnemer is heeft geen autorisatie voor indicatie onjuist (98410) # features\bevragen\autorisatie-gba.feature:302
    - Er staat rubrieknummer ad hoc 09210 maar dat moet zijn 90210.
 
##### Meerdere type validatie foutmeldingen is teveel van het goede op dit moment. --> opgelost in #1653
- [x] Scenario: Meerdere ongeldige parameters zijn opgegeven # features\bevragen\zoek-met-postcode-en-huisnummer\dev\fout-cases-gba.feature:193

##### adressering.aanschrijfwijze.aanspreekvorm mist de verwachting voor naam.aanduidingNaamgebruik
- [x] Scenario: Afnemer vraagt om aanschrijfwijze.aanspreekvorm en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen # features\bevragen\persoon\adressering\aanschrijfwijze\dev\autorisatie-gba.feature:43

##### Bepalen welke content types en accept header waardes ondersteunt worden.
- [X] features\bevragen\zoek-fout-cases-gba.feature --> wordt opgelost met #1690
    - Er zijn foutmeldingen waarde details niet overeenkomen met de API.
    - Tevens worden de codes ook niet genoemd in de scenario. Graag dit toevoegen

##### Aktenummer is te lang
- [x] features\bevragen\persoon\ouder\dev\ouders-gba.feature (5 stuks)

##### Alleen rechten hebben voor geboortedatum + postcode + huisnummer maar fields vraagt heel geboorte ---> geen issue, scenario is correct, implementatie niet. Zie https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/1598#issuecomment-1473977220
- [x] Scenario: Afnemer vraagt geboorte, en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen # features\bevragen\persoon-beperkt\geboorte\dev\autorisatie-gba.feature:70

##### Fouten rondom accept en contenttype in scenarios ---> wordt opgelost met #1697
- [x] Scenario: Lege Accept contenttype wordt ondersteund # features\bevragen\zoek-fout-cases-gba.feature:187
- [x] Scenario: Lege Content-Type wordt ondersteund # features\bevragen\zoek-fout-cases-gba.feature:200
    - Een lege string of afwezigheid van waarde is geaccepteerd want dan forceren we een default. Waarom verwachten we dan nul response? Deze BSN's kunnen response krijgen.
- [x] Scenario: Gevraagde Accept contenttype wordt niet ondersteund # features\bevragen\zoek-fout-cases-gba.feature:84
- [x] Scenario: 'application/xml' als Content-Type waarde wordt niet ondersteund # features\bevragen\zoek-fout-cases-gba.feature:179
- [x] Scenario: 'text/csv' als Content-Type waarde wordt niet ondersteund # features\bevragen\zoek-fout-cases-gba.feature:180
- [x] Scenario: 'application/json; charset=cp1252' als Content-Type waarde wordt niet ondersteund # features\bevragen\zoek-fout-cases-gba.feature:181
    - Verwacht de volgende detail 'Ondersteunde content type: */*, application/json, application/json; charset=utf-8, application/json;charset=utf-8. Default: application/json; charset=utf-8.' maar in werkelijkheid hoort dit het volgende te zijn: '"Ondersteunde content type: */*, */*;charset=utf-8, */*; charset=utf-8, application/json, application/json; charset=utf-8, application/json;charset=utf-8. Default: application/json; charset=utf-8.'
    - Ontbrekende stuk is gevolg van wijziging verzoek bij regel 126 en 127 in dezelfde feature.

##### Protocollering snapt niet waarom geslacht bij naam field meegenomen wordt ---> eerste twee punten worden opgelost met #1698
- [x] Scenario: vragen om hele groep naam # features\bevragen\protocollering-gba.feature:135
- [x] Scenario: Vragen om naam en persoon heeft geen adellijkeTitelPredicaat # features\bevragen\protocollering-gba.feature:183
- [x] Scenario: Met fields vragen om naam wordt vastgelegd als gevraagde rubrieken 010210, 010220, 010230, 010240, 010410 # features\bevragen\persoon-beperkt\naam\dev\protocollering-gevraagde-rubrieken-gba.feature:27 ---> Volgens mij is dit correct. Scenario slaagt ook op v1.0.38

##### Protocollering scenario verwacht alleen geboortedatum in gevraagde rubrieken terwijl fields heel groep geboorte omvat. @KayodeBakker dit betreft groep geboorte in PersoonBeperkt. Daarin zit alleen geboortedatum, er zit geen plaats of land. Dus volgens mij is scenario correct en implementatie niet correct
- [x] Scenario: Met fields vragen om geboorte wordt vastgelegd als gevraagde rubrieken 010310 # features\bevragen\persoon-beperkt\geboorte\dev\protocollering-gevraagde-rubrieken-gba.feature:27

##### Scenarios rondom protocollering specifiek op zoek bevragingen
- [x] Er moeten scenarios komen die de verschillen tussen persoon volledig en persoon beperkt controleren.
    - De reden hiervoor is omdat beiden bijv. naam en geboorte hebben, maar ze bevatten andere waardes (beperkt heeft bijv. geen geboorteplaats.) Dit moet worden gevalideerd dat een beperkt bevraging niet bij protocollering ook een geboorteplaats rubriek insert.

**Comment by fsamwel** [comment]
@KayodeBakker wat bedoel je in de laatste zin met "geslachtsaanduiding dat niet geslacht mag zijn"?

Dit scenario geeft nu het correcte resultaat met geslacht=V, maar geen resultaat bij geslacht=v. Aangezien het scenario gaat over de rule "geslacht is niet hoofdlettergevoelig" is m.i. het scenario nu correct, maar de implementatie nog niet (in v2.0.23)

**Comment by fsamwel** [comment]
@MelvLee jij bent volgens mij met de features op de overige punten bezig, toch?
- features\gba-dev\waardetabel-gba.feature

**Comment by fsamwel** [comment]
> Adressering/aanhef, aanschrijfwijze, gebruikInLopendeTekst horen aangaanHuwelijkPartnerschap/ontbindingHuwelijkPartnerschap aan te leveren volgens fields-gba van deze onderwerpen. Echter bij de volgende feature kan geen inOnderzoek worden getoond van bijv. aangaanHuwelijkPartnerschap
>- features\bevragen\persoon\adressering\dev\fields-gba.feature
>    - Dit is toch niet logisch? We hebben afspraken dat als je een bevraging doet van een object dat in onderzoek is, dat je automatisch het in onderzoek stuk terug krijgt? Door bijv. adressering.aanschrijfwijze te vragen in de fields, krijg je gegevens van aangaanHuwelijkPartnerschap terug en dus ook inOnderzoek.

@KayodeBakker Ik begrijp niet wat je bedoelt. In de scenario's komt aangaanHuwelijkPartnerschap niet voor in de Gegeven stap. Ook hebben we bij een partner in GbaPersoon alleen inOnderzoek op niveau van de partner, niet ook in aangaanHuwelijkPartnerschap.

Deze feature slaagt bij mij op v2.0.25. Bedoel je misschien een andere dan features\bevragen\persoon\adressering\dev\fields-gba.feature?

**Comment by fsamwel** [comment]
@MelvLee in features\bevragen\persoon\adressering\dev\fields-gba.feature hebben we op regels 63 en 64:
```
    | aanduiding in onderzoek | type                                 |
    | 056100                  | hele groep naamgebruik partner       |
    | 056110                  | aanduiding naamgebruik partner       |
```

Dat gegeven bestaat niet, bestaat alleen op de persoon. Willen we hier niet als voorbeelden onderzoek op aangaan huwelijk partnerschap en ontbinding huwelijk partnerschap?

**Comment by fsamwel** [comment]
>Immigratie.inOnderzoek is een proxy field en wordt vertaald bij de GBA naar verblijfplaats.inOnderzoek.
>- features\bevragen\persoon\rni\dev\overzicht-gba.feature:191
>   - Hier dient er geen lege verblijfplaats object te worden getoond, echter aangezien de field verblijfplaats.inOnderzoek wordt gebruikt en er geen inOnderzoek waarde is, zal dit een leeg object leveren. inOnderzoek moet daarentegen worden genegeerd. Wat te doen in deze casus? Moet heel immigratie.inOnderzoek worden genegeerd?

Volgens mij is de afspraak dat vragen om inOnderzoek volledig moet worden genegeerd. Die zou je uit de fields lijst kunnen wegfilteren en vervolgens een antwoord maken op basis van de gefilterde fields.

Met andere woorden: vragen om "fields": ["immigratie.inOnderzoek"] bij een persoon zonder onderzoek op verblijfplaats levert een persoon als leeg object.

**Comment by fsamwel** [comment]
> - features\bevragen\protocollering-gba.feature:156 (Scenario: vragen om hele relatie partners)
>   - Soort verbintenis maakt onderdeel uit van partners en ook hier inOnderzoek idem.

@KayodeBakker die zat er al in:
```
      Voorbeelden:
      | relatie  | gevraagde rubrieken                                                                                            |
      | partners | 050120, 050210, 050220, 050230, 050240, 050310, 050320, 050330, 050410, 050610, 050620, 050630, 050710, 051510 |
```

Bij het uitvoeren laat hij dat zien, maar vind het verschillend, omdat er in actual een komma achter staat (de inOnderzoek velden komen er immers nog achteraan):
```
           + expected - actual
              "050610,"
              "050620,"
              "050630,"
              "050710,"
           -  "051510,"
           -  "058310,"
           -  "058320"
           +  "051510"
```

**Comment by fsamwel** [comment]
> - features\bevragen\protocollering-gba.feature:279 (Abstract Scenario: Vragen om )
>   - adressering.aanschrijfwijze vertaalt naar 'naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap&partners.ontbindingHuwelijkPartnerschap'

@KayodeBakker ik zie in fields-mapping-gba.csv bij adressering.aanschrijfwijze:
naam|geslacht|partners.naam.adellijkeTitelPredicaat|partners.naam.voorvoegsel|partners.naam.geslachtsnaam|partners.aangaanHuwelijkPartnerschap.datum|partners.ontbindingHuwelijkPartnerschap.datum

Dus geen partners.aangaanHuwelijkPartnerschap.datum.plaats en geen partners.aangaanHuwelijkPartnerschap.datum.land

**Comment by KayodeBakker** [comment]
> 

Hoi Frank.
datum.plaats en datum.land bestaat niet dus ik neem aan dat de datum gedeelte ter overvloedden is, maar de fields-mapping-gba.csv is niet meer actueel en zou worden verwijderd. Het is dus niet verstandig om die en de beperkt variant te hanteren als waarheid.

Afspraak was dat alle fields-gba features de waarheid zijn. Die zouden tot in de uiterste detail zijn uitgezocht zodat er geen mapping ontbreekt of teveel wordt verwacht.

**Comment by KayodeBakker** [comment]
> > * Soort verbintenis maakt onderdeel uit van partners en ook hier inOnderzoek idem.

Ja okay dus soort verbintenis (en geboorteland kind) worden wel geleverd zoals correct en de scenario verwacht dit, maar omdat inOnderzoek ontbreekt zal deze falen. Dus blijft het nog bij de inOnderzoek en vergelijkbaar discussie.

**Comment by fsamwel** [comment]
> - features\bevragen\protocollering-gba.feature:322 (Abstract Scenario: Vragen om protocolleert ook benodigde velden voor het type)
>   - Veel rubrieken ontbreken in de scenario aangezien deze volgens fields-gba wel moeten worden geleverd bij deze field bevraging.

@KayodeBakker welke velden ontbreken volgens jou? Als ik deze draai zie ik de volgende verschillen:
           -  "050620,"
           -  "050630,"
           -  "058310,"
           -  "058320"

Zie eerdere opmerking over niet moeten leveren partners.aangaanHuwelijkPartnerschap.plaats en partners.aangaanHuwelijkPartnerschap.land (hier aanhef geldt hetzelfde als voor aanschrijfwijze).

Opnemen van inOnderzoek velden in protocollering bespreken we in overleg

**Comment by fsamwel** [comment]
> - features\bevragen\persoon\verblijfplaats\dev\protocollering-gevraagde-rubrieken-gba.feature:56 (Scenario: Met fields vragen om verblijfplaatsBinnenland.verblijfadres wordt vastgelegd als gevraagde rubrieken 081110, 081115, 081120, 081130, 081140, 081150, 081160, 081170, 081210)
>   - fields-gba features geven nergens aan dat 'verblijfplaatsBinnenland.verblijfadres' naamOpenbareRuimte en aanduiding bij huisnummer moet omvatten.

Dat is een omissie in die fields-gba feature. Waaruit had je geconcludeerd dat verblijfplaatsBinnenland deze velden niet bevat? Ik voeg het toe aan deze feature, zodat het ook expliciet wordt.

**Comment by fsamwel** [comment]
> adressering.aanschrijfwijze.aanspreekvorm mist de verwachting voor naam.aanduidingNaamgebruik
> - [ ] Scenario: Afnemer vraagt om aanschrijfwijze.aanspreekvorm en heeft uitsluitend de autorisatie die nodig is om deze vraag te mogen stellen # features\bevragen\persoon\adressering\aanschrijfwijze\dev\autorisatie-gba.feature:43

@KayodeBakker ik zie niet wat hier niet juist aan is. gaat het fout bij een ander scenario?

**Comment by fsamwel** [comment]
>  Scenario: Met fields vragen om naam wordt vastgelegd als gevraagde rubrieken 010210, 010220, 010230, 010240, 010410 # features\bevragen\persoon-beperkt\naam\dev\protocollering-gevraagde-rubrieken-gba.feature:27

@KayodeBakker wat is hier mis mee? Dit is persoon-beperkt, dus zit aanduidingNaamgebruik er niet in. Had je die ook verwacht?

**Comment by fsamwel** [comment]
> **Protocollering scenario verwacht alleen geboortedatum in gevraagde rubrieken terwijl fields heel groep geboorte omvat.** 
>
> - [ ] Scenario: Met fields vragen om geboorte wordt vastgelegd als gevraagde rubrieken 010310 # features\bevragen\persoon-beperkt\geboorte\dev\protocollering-gevraagde-rubrieken-gba.feature:27

@KayodeBakker dit betreft groep geboorte in PersoonBeperkt. Daarin zit alleen geboortedatum, er zit geen plaats of land. Dus volgens mij is scenario correct en implementatie niet correct

**Comment by fsamwel** [comment]
>  Er moeten scenarios komen die de verschillen tussen persoon volledig en persoon beperkt controleren. 
De reden hiervoor is omdat beiden bijv. naam en geboorte hebben, maar ze bevatten andere waardes (beperkt heeft bijv. geen geboorteplaats.) Dit moet worden gevalideerd dat een beperkt bevraging niet bij protocollering ook een geboorteplaats rubriek insert.

@KayodeBakker volgens mij zijn die scenario's er al. Heb jij voorbeelden van iets dat ik gemist heb?

**Comment by CathyDingemanse** [comment]
tijd om te sluiten!
