### ISSUE TITLE
Personen API v2.3 zoeken met pc/hn uitbreiden met geboortedatum

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bevragen#1824]
Datum in productie: 2 september

- [x] OAS. [toevoegen geboortedatum parameter + ophogen minor versie](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pull/1816)
- [ ] A&P [toevoegen validatie geboortedatum parameter + ophogen minor versie](https://github.com/BRP-API/brp-shared-dotnet/pull/41)
- [x] Dataservice. [implementatie + versie nr](https://github.com/BRP-API/haal-centraal/pull/2), [scenarios](https://github.com/BRP-API/personen-data-service/pull/9)
- [x] Informatieservice. [implementatie + versie nr + scenarios](https://github.com/BRP-API/personen-informatie-service/pull/7)
- [ ] personen mock

Uitgangspunt: verdeeld over meer dan 1 POD (gezagsmodule apart)
